name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '9'

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma client
        run: pnpm --filter @quick-status/db generate

      - name: Build packages
        run: pnpm run build

      - name: Setup test database
        run: |
          cd packages/db
          rm -f *.db test.db
          DATABASE_URL="file:./test.db" npx prisma db push --force-reset
          # Ensure foreign keys are enabled in CI
          echo "PRAGMA foreign_keys = ON;" | sqlite3 test.db
        env:
          DATABASE_URL: file:./test.db

      - name: Run lint
        run: pnpm lint

      - name: Run tests
        run: pnpm test
        env:
          DATABASE_URL: file:./test.db
          
  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4