name: Docker Build and Push

on:
  push:
    branches: [main, dev]
    paths:
      - 'docker/**'
      - 'apps/**'
      - 'packages/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'turbo.json'
  pull_request:
    branches: [main, dev]
    paths:
      - 'docker/**'
      - 'apps/**'
      - 'packages/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'turbo.json'
  workflow_dispatch: # Allow manual trigger

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        architecture: [amd64] # Run on both platforms
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU # Enable multi-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-,enable={{is_default_branch}}
            type=sha,prefix=pr-,enable=${{ github.event_name == 'pull_request' }}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build Docker Image and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/images/quick-status/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/${{ matrix.architecture }}
          tags: | # push it to quick-status/quick-status:architecture, e.g quick-status/quick-status:amd64
            ${{ env.IMAGE_NAME }}:${{ matrix.architecture }}-${{ github.sha }}
            ${{ env.IMAGE_NAME }}:${{ matrix.architecture }}
            ghcr.io/${{ env.IMAGE_NAME }}:${{ matrix.architecture }}-${{ github.sha }}
            ghcr.io/${{ env.IMAGE_NAME }}:${{ matrix.architecture }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 